### PR TITLE
scanning_drift_corr v1.0.1

### PR DESCRIPTION
**Pull request by ptim0626**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This version fixes the issue in Windows and macOS, so now the package should be able to build on Windows and macOS.

### CODE REVIEW

**Comment by ptim0626** [comment]
@conda-forge-admin, please rerender

**Comment by ptim0626** [comment]
@conda-forge/core

**Comment by dopplershift** [comment]
Why are you pinging core? Since you're already the maintainer, you're free to merge as you see fit.

**Comment by ptim0626** [comment]
@conda-forge-admin, please rerender

**Comment by ptim0626** [comment]
@dopplershift The rerender bot said there were some issue and asked me to ping core for further assistance. But I tried again the rerender and now seems ok, thanks!

**Pull request merged**
